spring:
    profiles:
        active:
        - dev
----------------------------
server:
    port: 8001
    
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.git.mm.mysql.Drover
        url: jdbc:mysql://localhost:3306/sd_dept
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
            
mybatis:
    config-location: classpath:mybatis/mybatisconfig.xml
    type-aliases-package: cn.wl.pojo
    mapper-location:
    - classpath:mybatis/mapper/**/*.xml

eureka:
    client:       #客户端注册进eureka服务列表
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: microservicecloud-dept8001       #自定义的服务名称信息
        prefer-ip-address: true                       #访问路径可以显示IP地址
    
#########配置注册进Eureka的info信息
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
    

       